// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1.proto

package com.cpcb.gs;

public final class RpcMessage {
  private RpcMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ckcb.gs.RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
     */
    com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getHeader();
    /**
     * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
     */
    com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.ckcb.gs.RpcRequest}
   */
  public  static final class RpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ckcb.gs.RpcRequest)
      RpcRequestOrBuilder {
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcRequest() {
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cpcb.gs.RpcMessage.RpcRequest.class, com.cpcb.gs.RpcMessage.RpcRequest.Builder.class);
    }

    public interface RequestHeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ckcb.gs.RpcRequest.RequestHeader)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 rpcId = 1;</code>
       */
      int getRpcId();

      /**
       * <code>optional int32 reqId = 2;</code>
       */
      int getReqId();
    }
    /**
     * Protobuf type {@code com.ckcb.gs.RpcRequest.RequestHeader}
     */
    public  static final class RequestHeader extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ckcb.gs.RpcRequest.RequestHeader)
        RequestHeaderOrBuilder {
      // Use RequestHeader.newBuilder() to construct.
      private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private RequestHeader() {
        rpcId_ = 0;
        reqId_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private RequestHeader(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                rpcId_ = input.readInt32();
                break;
              }
              case 16: {

                reqId_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.class, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder.class);
      }

      public static final int RPCID_FIELD_NUMBER = 1;
      private int rpcId_;
      /**
       * <code>optional int32 rpcId = 1;</code>
       */
      public int getRpcId() {
        return rpcId_;
      }

      public static final int REQID_FIELD_NUMBER = 2;
      private int reqId_;
      /**
       * <code>optional int32 reqId = 2;</code>
       */
      public int getReqId() {
        return reqId_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (rpcId_ != 0) {
          output.writeInt32(1, rpcId_);
        }
        if (reqId_ != 0) {
          output.writeInt32(2, reqId_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (rpcId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, rpcId_);
        }
        if (reqId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, reqId_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader)) {
          return super.equals(obj);
        }
        com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader other = (com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader) obj;

        boolean result = true;
        result = result && (getRpcId()
            == other.getRpcId());
        result = result && (getReqId()
            == other.getReqId());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + RPCID_FIELD_NUMBER;
        hash = (53 * hash) + getRpcId();
        hash = (37 * hash) + REQID_FIELD_NUMBER;
        hash = (53 * hash) + getReqId();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.ckcb.gs.RpcRequest.RequestHeader}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ckcb.gs.RpcRequest.RequestHeader)
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.class, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder.class);
        }

        // Construct using com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          rpcId_ = 0;

          reqId_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor;
        }

        public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getDefaultInstanceForType() {
          return com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance();
        }

        public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader build() {
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader buildPartial() {
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader result = new com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader(this);
          result.rpcId_ = rpcId_;
          result.reqId_ = reqId_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader) {
            return mergeFrom((com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader other) {
          if (other == com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance()) return this;
          if (other.getRpcId() != 0) {
            setRpcId(other.getRpcId());
          }
          if (other.getReqId() != 0) {
            setReqId(other.getReqId());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int rpcId_ ;
        /**
         * <code>optional int32 rpcId = 1;</code>
         */
        public int getRpcId() {
          return rpcId_;
        }
        /**
         * <code>optional int32 rpcId = 1;</code>
         */
        public Builder setRpcId(int value) {
          
          rpcId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 rpcId = 1;</code>
         */
        public Builder clearRpcId() {
          
          rpcId_ = 0;
          onChanged();
          return this;
        }

        private int reqId_ ;
        /**
         * <code>optional int32 reqId = 2;</code>
         */
        public int getReqId() {
          return reqId_;
        }
        /**
         * <code>optional int32 reqId = 2;</code>
         */
        public Builder setReqId(int value) {
          
          reqId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 reqId = 2;</code>
         */
        public Builder clearReqId() {
          
          reqId_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.ckcb.gs.RpcRequest.RequestHeader)
      }

      // @@protoc_insertion_point(class_scope:com.ckcb.gs.RpcRequest.RequestHeader)
      private static final com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader();
      }

      public static com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<RequestHeader>
          PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
        public RequestHeader parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new RequestHeader(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<RequestHeader> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<RequestHeader> getParserForType() {
        return PARSER;
      }

      public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader header_;
    /**
     * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
     */
    public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getHeader() {
      return header_ == null ? com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
     */
    public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!content_.isEmpty()) {
        output.writeBytes(2, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cpcb.gs.RpcMessage.RpcRequest)) {
        return super.equals(obj);
      }
      com.cpcb.gs.RpcMessage.RpcRequest other = (com.cpcb.gs.RpcMessage.RpcRequest) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cpcb.gs.RpcMessage.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cpcb.gs.RpcMessage.RpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ckcb.gs.RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ckcb.gs.RpcRequest)
        com.cpcb.gs.RpcMessage.RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cpcb.gs.RpcMessage.RpcRequest.class, com.cpcb.gs.RpcMessage.RpcRequest.Builder.class);
      }

      // Construct using com.cpcb.gs.RpcMessage.RpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcRequest_descriptor;
      }

      public com.cpcb.gs.RpcMessage.RpcRequest getDefaultInstanceForType() {
        return com.cpcb.gs.RpcMessage.RpcRequest.getDefaultInstance();
      }

      public com.cpcb.gs.RpcMessage.RpcRequest build() {
        com.cpcb.gs.RpcMessage.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cpcb.gs.RpcMessage.RpcRequest buildPartial() {
        com.cpcb.gs.RpcMessage.RpcRequest result = new com.cpcb.gs.RpcMessage.RpcRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cpcb.gs.RpcMessage.RpcRequest) {
          return mergeFrom((com.cpcb.gs.RpcMessage.RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cpcb.gs.RpcMessage.RpcRequest other) {
        if (other == com.cpcb.gs.RpcMessage.RpcRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cpcb.gs.RpcMessage.RpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cpcb.gs.RpcMessage.RpcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      public Builder setHeader(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      public Builder setHeader(
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      public Builder mergeHeader(com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      public com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>optional .com.ckcb.gs.RpcRequest.RequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeader.Builder, com.cpcb.gs.RpcMessage.RpcRequest.RequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.ckcb.gs.RpcRequest)
    }

    // @@protoc_insertion_point(class_scope:com.ckcb.gs.RpcRequest)
    private static final com.cpcb.gs.RpcMessage.RpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cpcb.gs.RpcMessage.RpcRequest();
    }

    public static com.cpcb.gs.RpcMessage.RpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RpcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    public com.cpcb.gs.RpcMessage.RpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ckcb.gs.RpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
     */
    com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getHeader();
    /**
     * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
     */
    com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.ckcb.gs.RpcResponse}
   */
  public  static final class RpcResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ckcb.gs.RpcResponse)
      RpcResponseOrBuilder {
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcResponse() {
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cpcb.gs.RpcMessage.RpcResponse.class, com.cpcb.gs.RpcMessage.RpcResponse.Builder.class);
    }

    public interface ResponseHeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ckcb.gs.RpcResponse.ResponseHeader)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 reqId = 1;</code>
       */
      int getReqId();
    }
    /**
     * Protobuf type {@code com.ckcb.gs.RpcResponse.ResponseHeader}
     */
    public  static final class ResponseHeader extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ckcb.gs.RpcResponse.ResponseHeader)
        ResponseHeaderOrBuilder {
      // Use ResponseHeader.newBuilder() to construct.
      private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ResponseHeader() {
        reqId_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private ResponseHeader(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                reqId_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.class, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder.class);
      }

      public static final int REQID_FIELD_NUMBER = 1;
      private int reqId_;
      /**
       * <code>optional int32 reqId = 1;</code>
       */
      public int getReqId() {
        return reqId_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (reqId_ != 0) {
          output.writeInt32(1, reqId_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (reqId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, reqId_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader)) {
          return super.equals(obj);
        }
        com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader other = (com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader) obj;

        boolean result = true;
        result = result && (getReqId()
            == other.getReqId());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + REQID_FIELD_NUMBER;
        hash = (53 * hash) + getReqId();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.ckcb.gs.RpcResponse.ResponseHeader}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ckcb.gs.RpcResponse.ResponseHeader)
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.class, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder.class);
        }

        // Construct using com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          reqId_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor;
        }

        public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getDefaultInstanceForType() {
          return com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance();
        }

        public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader build() {
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader buildPartial() {
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader result = new com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader(this);
          result.reqId_ = reqId_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader) {
            return mergeFrom((com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader other) {
          if (other == com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance()) return this;
          if (other.getReqId() != 0) {
            setReqId(other.getReqId());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int reqId_ ;
        /**
         * <code>optional int32 reqId = 1;</code>
         */
        public int getReqId() {
          return reqId_;
        }
        /**
         * <code>optional int32 reqId = 1;</code>
         */
        public Builder setReqId(int value) {
          
          reqId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 reqId = 1;</code>
         */
        public Builder clearReqId() {
          
          reqId_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:com.ckcb.gs.RpcResponse.ResponseHeader)
      }

      // @@protoc_insertion_point(class_scope:com.ckcb.gs.RpcResponse.ResponseHeader)
      private static final com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader();
      }

      public static com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ResponseHeader>
          PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
        public ResponseHeader parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new ResponseHeader(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ResponseHeader> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
        return PARSER;
      }

      public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader header_;
    /**
     * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
     */
    public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getHeader() {
      return header_ == null ? com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
     */
    public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!content_.isEmpty()) {
        output.writeBytes(2, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cpcb.gs.RpcMessage.RpcResponse)) {
        return super.equals(obj);
      }
      com.cpcb.gs.RpcMessage.RpcResponse other = (com.cpcb.gs.RpcMessage.RpcResponse) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cpcb.gs.RpcMessage.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cpcb.gs.RpcMessage.RpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ckcb.gs.RpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ckcb.gs.RpcResponse)
        com.cpcb.gs.RpcMessage.RpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cpcb.gs.RpcMessage.RpcResponse.class, com.cpcb.gs.RpcMessage.RpcResponse.Builder.class);
      }

      // Construct using com.cpcb.gs.RpcMessage.RpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cpcb.gs.RpcMessage.internal_static_com_ckcb_gs_RpcResponse_descriptor;
      }

      public com.cpcb.gs.RpcMessage.RpcResponse getDefaultInstanceForType() {
        return com.cpcb.gs.RpcMessage.RpcResponse.getDefaultInstance();
      }

      public com.cpcb.gs.RpcMessage.RpcResponse build() {
        com.cpcb.gs.RpcMessage.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cpcb.gs.RpcMessage.RpcResponse buildPartial() {
        com.cpcb.gs.RpcMessage.RpcResponse result = new com.cpcb.gs.RpcMessage.RpcResponse(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cpcb.gs.RpcMessage.RpcResponse) {
          return mergeFrom((com.cpcb.gs.RpcMessage.RpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cpcb.gs.RpcMessage.RpcResponse other) {
        if (other == com.cpcb.gs.RpcMessage.RpcResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cpcb.gs.RpcMessage.RpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cpcb.gs.RpcMessage.RpcResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      public com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>optional .com.ckcb.gs.RpcResponse.ResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeader.Builder, com.cpcb.gs.RpcMessage.RpcResponse.ResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.ckcb.gs.RpcResponse)
    }

    // @@protoc_insertion_point(class_scope:com.ckcb.gs.RpcResponse)
    private static final com.cpcb.gs.RpcMessage.RpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cpcb.gs.RpcMessage.RpcResponse();
    }

    public static com.cpcb.gs.RpcMessage.RpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<RpcResponse>() {
      public RpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RpcResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcResponse> getParserForType() {
      return PARSER;
    }

    public com.cpcb.gs.RpcMessage.RpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ckcb_gs_RpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ckcb_gs_RpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ckcb_gs_RpcRequest_RequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ckcb_gs_RpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ckcb_gs_RpcResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0071.proto\022\013com.ckcb.gs\"\203\001\n\nRpcRequest\0225\n" +
      "\006header\030\001 \001(\0132%.com.ckcb.gs.RpcRequest.R" +
      "equestHeader\022\017\n\007content\030\002 \001(\014\032-\n\rRequest" +
      "Header\022\r\n\005rpcId\030\001 \001(\005\022\r\n\005reqId\030\002 \001(\005\"x\n\013" +
      "RpcResponse\0227\n\006header\030\001 \001(\0132\'.com.ckcb.g" +
      "s.RpcResponse.ResponseHeader\022\017\n\007content\030" +
      "\002 \001(\014\032\037\n\016ResponseHeader\022\r\n\005reqId\030\001 \001(\005B\031" +
      "\n\013com.cpcb.gsB\nRpcMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ckcb_gs_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ckcb_gs_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ckcb_gs_RpcRequest_descriptor,
        new java.lang.String[] { "Header", "Content", });
    internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor =
      internal_static_com_ckcb_gs_RpcRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_ckcb_gs_RpcRequest_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ckcb_gs_RpcRequest_RequestHeader_descriptor,
        new java.lang.String[] { "RpcId", "ReqId", });
    internal_static_com_ckcb_gs_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ckcb_gs_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ckcb_gs_RpcResponse_descriptor,
        new java.lang.String[] { "Header", "Content", });
    internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor =
      internal_static_com_ckcb_gs_RpcResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ckcb_gs_RpcResponse_ResponseHeader_descriptor,
        new java.lang.String[] { "ReqId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
